### ISSUE TITLE
"Inventory" tab is displaying after plublish the GC Product

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#10]
"Inventory" tab is displaying after published the GC Product
![image](https://user-images.githubusercontent.com/25762796/64029694-c0990c80-cb62-11e9-95d3-3d8ff8378a29.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
Feature added in Premium version
