### ISSUE TITLE
"Giftcard No of time usage" is not accepting any value

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#11]
"Giftcard No of time usage" under Gift Card > General Settings is not accepting any value.
![image](https://user-images.githubusercontent.com/25762796/64059997-2da0b680-cbe4-11e9-96aa-5d636cb12cc9.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
