### ISSUE TITLE
After selecting "Email Background color" template should display properly

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#12]
After selecting "Email Background color" template should display properly
![image](https://user-images.githubusercontent.com/25762796/64061266-08b53f00-cbf6-11e9-8ee5-b075d24c35fa.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
