### ISSUE TITLE
Tooltip should display properly of "Email Background Color" 

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#13]
Tooltip should display properly of "Email Background Color". It should display in front of the color picker

![image](https://user-images.githubusercontent.com/25762796/64092009-8d2bcd00-cd70-11e9-83c7-f50b54c8d7b5.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
Done
