### ISSUE TITLE
"Giftcard Message Length" default should be 300

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#14]
"Giftcard Message Length" default should be 300. It's displaying 0.
![image](https://user-images.githubusercontent.com/25762796/64092138-117e5000-cd71-11e9-8794-a99b89ac262b.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
