### ISSUE TITLE
Need to change Sub-Heading of "delivery methods"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#15]
Need to change Sub-Heading of "delivery methods"
![image](https://user-images.githubusercontent.com/25762796/64093929-b2700980-cd77-11e9-8939-53cc19b10637.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
