### ISSUE TITLE
Need to change description of " Delivery Method" on Product Page

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#16]
Need to change the description of " Delivery Method" on Product Page
![image](https://user-images.githubusercontent.com/25762796/64094374-252db480-cd79-11e9-8b33-47022b206976.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
