### ISSUE TITLE
[SITENAME] shortcode is not working

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#17]
[SITENAME] shortcode is not working under Email template > Mail Setting section
![image](https://user-images.githubusercontent.com/25762796/64106011-f1f91e80-cd94-11e9-9d55-8fca9c9b50c0.png)

**Comment by Snehlata-Sharma** [comment]
FIXED

**Comment by anshucedcoss** [comment]
DONE
