### ISSUE TITLE
Need to change setting descripton under "Other Setting" tab

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#19]
Need to change setting description under "Other Setting" tab.
![image](https://user-images.githubusercontent.com/25762796/64112044-d5b0ae00-cda3-11e9-9a05-107a5d80e1d3.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
