### ISSUE TITLE
When Activate Gift Card plugin and WooCommerce is not active then a warning message is displaying

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#2]
When Activate Gift Card plugin and WooCommerce is not active then a warning message is displaying.
![image](https://user-images.githubusercontent.com/25762796/64017874-4cea0600-cb48-11e9-8f8f-42f349f05e70.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by indresh-cedcoss** [comment]
fixed
