### ISSUE TITLE
"Giftcard No of time usage" default value should be zero(0)

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#20]
"Giftcard No of time usage" default value should be zero(0)
![image](https://user-images.githubusercontent.com/25762796/64123451-0acbf900-cdc2-11e9-8d71-427499cd1bf5.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
