### ISSUE TITLE
"Minimum Spend" and "Maximum Spend" accepting default value "0"

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#22]
"Minimum Spend" and "Maximum Spend" should not accept 0 value"

Default it should display like- "No Minimum" and "No Maximum".

![image](https://user-images.githubusercontent.com/25762796/64846299-f42b6a80-d629-11e9-9b4d-1b1da9ae6c01.png)

**Comment by indresh-cedcoss** [comment]
fixed
