### ISSUE TITLE
In [BUYEREMAILADDRESS] shortcode Buyer name is displaying

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#23]
In [BUYEREMAILADDRESS] shortcode Buyer name is displaying.
In this shortcode, buyer name should get the display.

![image](https://user-images.githubusercontent.com/25762796/64848179-48d0e480-d62e-11e9-9f65-21f53034a4aa.png)

**Comment by indresh-cedcoss** [comment]
fixed

**Comment by indresh-cedcoss** [comment]
fixed
