### ISSUE TITLE
When update the plugin then displaying error message on the gift card product page

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#35]
When updating the plugin then displaying an error message on the gift card product page
![image](https://user-images.githubusercontent.com/25762796/73744583-13f93180-4777-11ea-95af-35b60e487207.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
