### ISSUE TITLE
Need to change feature image of 2 templates

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#38]
Need to change feature image of 2 templates
Custom Template
Merry Christmas Template
![image](https://user-images.githubusercontent.com/25762796/73847775-ee3e5c00-484c-11ea-9ad8-8f00cc5ae2e2.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
