### ISSUE TITLE
When clicking on the Notification "Dismiss" button then Blank page is opening

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#4]
When clicking on the Notification "Dismiss" button then Blank page is opening.
![image](https://user-images.githubusercontent.com/25762796/64018261-96872080-cb49-11e9-8135-5c26aa22ca83.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE.
