### ISSUE TITLE
When Scroll the settings then the sidebar should be fixed.

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#41]
When Scroll the settings then the sidebar should be fixed.
![image](https://user-images.githubusercontent.com/25762796/74314064-d27e0d00-4d9a-11ea-89e9-29e8ba24da33.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
