### ISSUE TITLE
When WooCommerce is not Activated and Gift Card Activere then two messages are displaying

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#43]
When WooCommerce is not Activated and Gift Card Active then two messages are displaying
![image](https://user-images.githubusercontent.com/25762796/75017898-f8e72b00-54b3-11ea-8d28-3017d2d3825d.png)

**Comment by Snehlata-Sharma** [comment]
fixed
