### ISSUE TITLE
When select any price type then desigin is displaying messy on product page

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#9]
After selecting price type - User price, Price Range, Selected price from backend the desigin is displaying messy on the product page.
Price Range--
![image](https://user-images.githubusercontent.com/25762796/64025690-e1f5fa80-cb5a-11e9-821c-51e6ada01845.png)

Selected Price--
![image](https://user-images.githubusercontent.com/25762796/64025853-4022dd80-cb5b-11e9-9ab8-667b35352b71.png)

User Price--
![image](https://user-images.githubusercontent.com/25762796/64026050-a4de3800-cb5b-11e9-85fa-e2404c390ab0.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
DONE
